# Generated by Django 2.2.10 on 2020-05-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalogue_filters.Attribute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='catalogue_filters.Attribute')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='catalogue.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs', to='catalogue_filters.CategoryAttribute')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs', to='catalogue.Product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs', to='catalogue_filters.AttributeValue')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_values', to='catalogue_filters.CategoryAttribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_values', to='catalogue_filters.AttributeValue')),
            ],
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='values',
            field=models.ManyToManyField(through='catalogue_filters.CategoryAttributeValue', to='catalogue_filters.AttributeValue'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('parent', 'attribute')},
        ),
    ]
