# Generated by Django 2.2.10 on 2020-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_filters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.ManyToManyField(related_name='product_attrs', to='catalogue_filters.AttributeValue'),
        ),
    ]
