# Generated by Django 2.2.10 on 2020-05-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue_filters', '0002_auto_20200526_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs', to='catalogue_filters.AttributeValue'),
            preserve_default=False,
        ),
    ]
