# Generated by Django 2.2.10 on 2020-12-09 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('base', models.BooleanField(default=False, verbose_name='Базовая валюта')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['-base'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=200, verbose_name='Обменный курс')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Валюта', to='currency.Currency')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='currency.Currency')),
            ],
            options={
                'verbose_name': 'Обменный курс',
                'verbose_name_plural': 'Обменные курсы',
                'ordering': ('currency',),
                'unique_together': {('parent', 'currency')},
            },
        ),
    ]
