# Generated by Django 2.2.10 on 2020-05-11 10:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('zh-hans', '中国'), ('en', 'ENG'), ('ru', 'РУС'), ('uk', 'УКР')], max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Активный язык',
                'verbose_name_plural': 'Активные языки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время отправки')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='core.Country')),
            ],
            options={
                'verbose_name': 'country (перевод)',
                'verbose_name_plural': 'countrys (перевод)',
            },
        ),
    ]
