# Generated by Django 2.2.10 on 2020-12-09 15:47

import apps.documents.models.models__invoice
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoterms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=200, verbose_name='Ставка перевозчика')),
                ('formula', models.CharField(help_text='Цену подставлять в виде английского "x"', max_length=255, validators=[apps.documents.models.models__invoice.priceFormulaValidator], verbose_name='Формула подсчета')),
            ],
            options={
                'verbose_name': 'Инкотермс',
                'verbose_name_plural': 'Инкотермс',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('file', models.FileField(null=True, upload_to='temp')),
                ('file_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('ext', models.CharField(blank=True, editable=False, max_length=100, verbose_name='file extension')),
            ],
            options={
                'verbose_name': 'Шаблон инвойса',
                'verbose_name_plural': 'Шаблоны инвойсов',
            },
        ),
        migrations.CreateModel(
            name='PriceFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(help_text='Цену подставлять в виде английского "x"', max_length=255, validators=[apps.documents.models.models__invoice.priceFormulaValidator], verbose_name='Формула подсчета')),
            ],
            options={
                'verbose_name': 'Формула цены',
                'verbose_name_plural': 'Формулы цен',
                'ordering': ['formula'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код')),
                ('date', models.DateField(verbose_name='Дата')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('incoterms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoterms', to='documents.Incoterms')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.PriceFormula')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.InvoiceTemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Колличество')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='documents.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Product')),
            ],
            options={
                'unique_together': {('invoice', 'product')},
            },
        ),
    ]
