# Generated by Django 2.2.10 on 2020-05-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoterms',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=200, verbose_name='Ставка перевозчика'),
        ),
    ]
