# Generated by Django 2.2.10 on 2020-05-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_incoterms_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicetemplate',
            options={'verbose_name': 'Шаблон инвойса', 'verbose_name_plural': 'Шаблоны инвойсов'},
        ),
    ]
