# Generated by Django 2.2.10 on 2020-12-09 15:47

import ckeditor.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('price', models.DecimalField(decimal_places=2, default=1.25, max_digits=200, verbose_name='Наценка, розница')),
                ('sm_price', models.DecimalField(decimal_places=2, default=1.1, max_digits=200, verbose_name='Наценка, мелкий опт')),
                ('sm_start', models.PositiveIntegerField(blank=True, default=10, verbose_name='Начало малого опта')),
                ('md_price', models.DecimalField(decimal_places=2, default=1.05, max_digits=200, verbose_name='Наценка, средний опт')),
                ('md_start', models.PositiveIntegerField(blank=True, default=20, verbose_name='Начало среднгего опта')),
                ('bg_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=200, verbose_name='Наценка, крупный опт')),
                ('bg_start', models.PositiveIntegerField(blank=True, default=40, verbose_name='Начало большого опта')),
                ('ignore_multiply', models.BooleanField(default=False, verbose_name='Без наценки')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('customs_code', models.CharField(blank=True, max_length=255, verbose_name='УКТЗЕД')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Идентификатор')),
                ('price_box', models.BooleanField(default=False, verbose_name='Цена за ящик')),
                ('entry_price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена')),
                ('price_ua', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена UA')),
                ('price_old', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Старая цена')),
                ('price_old_ua', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Старая цена UA')),
                ('sm_whoosale', models.BooleanField(default=True, verbose_name='Малый опт')),
                ('sm_price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, мелкий опт')),
                ('sm_price_ua', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, мелкий опт UA')),
                ('sm_start', models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало малого опта')),
                ('md_whoosale', models.BooleanField(default=True, verbose_name='Средний опт')),
                ('md_price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, средний опт')),
                ('md_price_ua', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, средний опт UA')),
                ('md_start', models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало среднгего опта')),
                ('bg_whoosale', models.BooleanField(default=True, verbose_name='Крупный опт')),
                ('bg_price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, крупный опт')),
                ('bg_price_ua', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, крупный опт UA')),
                ('bg_start', models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало большого опта')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('box_w', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='W, см')),
                ('box_l', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='L, см')),
                ('box_h', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='H, см')),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=200, verbose_name='Обьем')),
                ('weight_netto', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Вес, нетто')),
                ('weight_brutto', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Вес, брутто')),
                ('volume_weight', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Обьемный вес')),
                ('pieces_in_box', models.PositiveIntegerField(default=1, verbose_name='Шт. в ящике')),
                ('pieces_in_pack', models.PositiveIntegerField(default=1, verbose_name='Шт. в упаковке')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечания')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('view', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('num', models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('file', models.FileField(null=True, upload_to='temp')),
                ('file_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('ext', models.CharField(blank=True, editable=False, max_length=100, verbose_name='file extension')),
                ('name', models.CharField(choices=[('DESCRIPTION', 'Описание'), ('PRESENTATION', 'Презентация'), ('METHOD', 'Способ применения')], max_length=100, verbose_name='Тип документа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('customs_code', models.CharField(blank=True, max_length=255, verbose_name='УКТЗЕД')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечания')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Товар (перевод)',
                'verbose_name_plural': 'Товары (перевод)',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена')),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'История цен',
                'verbose_name_plural': 'История цен',
                'ordering': ['-update'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image', models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='Изображение')),
                ('image_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocumentsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('file_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('ext', models.CharField(blank=True, editable=False, max_length=100, verbose_name='file extension')),
                ('name', models.CharField(choices=[('DESCRIPTION', 'Описание'), ('PRESENTATION', 'Презентация'), ('METHOD', 'Способ применения')], max_length=100, verbose_name='Тип документа')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='catalogue.ProductDocuments')),
            ],
            options={
                'verbose_name': 'Документ (перевод)',
                'verbose_name_plural': 'Документы (перевод)',
            },
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('file', models.FileField(null=True, upload_to='temp')),
                ('file_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('ext', models.CharField(blank=True, editable=False, max_length=100, verbose_name='file extension')),
                ('name', models.CharField(choices=[('FDA', 'FDA'), ('CE', 'CE'), ('CHI', 'CHI')], max_length=100, verbose_name='Тип сертфиката')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='catalogue.Category')),
            ],
            options={
                'verbose_name': 'Категория (перевод)',
                'verbose_name_plural': 'Категории (перевод)',
            },
        ),
    ]
