# Generated by Django 2.2.10 on 2020-05-11 10:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('sm_price', models.DecimalField(decimal_places=2, default=1.1, max_digits=200, verbose_name='Наценка, мелкий опт')),
                ('md_price', models.DecimalField(decimal_places=2, default=1.05, max_digits=200, verbose_name='Наценка, средний опт')),
                ('bg_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=200, verbose_name='Наценка, крупный опт')),
                ('ignore_multiply', models.BooleanField(default=False, verbose_name='Без наценки')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('customs_code', models.CharField(blank=True, max_length=255, verbose_name='УКТЗЕД')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Идентификатор')),
                ('price_box', models.BooleanField(default=False, verbose_name='Цена за ящик')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена')),
                ('price_old', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Старая цена')),
                ('price_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('sm_whoosale', models.BooleanField(default=True, verbose_name='Малый опт')),
                ('sm_price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, мелкий опт')),
                ('md_whoosale', models.BooleanField(default=True, verbose_name='Средний опт')),
                ('md_price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, средний опт')),
                ('bg_whoosale', models.BooleanField(default=True, verbose_name='Крупный опт')),
                ('bg_price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена, крупный опт')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('delivery_time', models.DateField(blank=True, null=True, verbose_name='Время поставки')),
                ('stnadrt_eu', models.CharField(blank=True, default='', max_length=255)),
                ('stnadrt_us', models.CharField(blank=True, default='', max_length=255)),
                ('stnadrt_cn', models.CharField(blank=True, default='', max_length=255)),
                ('box_w', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='W, см')),
                ('box_l', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='L, см')),
                ('box_h', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='H, см')),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=200, verbose_name='Обьем')),
                ('weight_netto', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Вес, нетто')),
                ('weight_brutto', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Вес, брутто')),
                ('volume_weight', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Обьемный вес')),
                ('pieces_in_box', models.PositiveIntegerField(default=1, verbose_name='Шт. в ящике')),
                ('pieces_in_pack', models.PositiveIntegerField(default=1, verbose_name='Шт. в упаковке')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечания')),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('file', models.FileField(null=True, upload_to='temp')),
                ('file_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('ext', models.CharField(blank=True, editable=False, max_length=100, verbose_name='file extension')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('name', models.CharField(choices=[('DESCRIPTION', 'Описание'), ('PRESENTATION', 'Презентация'), ('METHOD', 'Способ применения')], max_length=100, verbose_name='Тип документа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='catalogue.ProductType')),
            ],
            options={
                'verbose_name': 'Тип товара (перевод)',
                'verbose_name_plural': 'Типы товаров (перевод)',
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('customs_code', models.CharField(blank=True, max_length=255, verbose_name='УКТЗЕД')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('stnadrt_eu', models.CharField(blank=True, default='', max_length=255)),
                ('stnadrt_us', models.CharField(blank=True, default='', max_length=255)),
                ('stnadrt_cn', models.CharField(blank=True, default='', max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечания')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Товар (перевод)',
                'verbose_name_plural': 'Товары (перевод)',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер')),
                ('image_l', models.ImageField(max_length=1000, null=True, upload_to='')),
                ('image_l_size', models.CharField(blank=True, editable=False, max_length=1000)),
                ('image_l_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('image_s', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('image_s_size', models.CharField(blank=True, editable=False, max_length=1000)),
                ('image_s_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('image_xs', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('image_xs_size', models.CharField(blank=True, editable=False, max_length=1000)),
                ('image_xs_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('image_sq', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_sq_size', models.CharField(blank=True, editable=False, max_length=1000)),
                ('image_sq_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('regen', models.BooleanField(default=False)),
                ('ext', models.CharField(blank=True, default='jpeg', editable=False, max_length=100, verbose_name='file extension')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['-num'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocumentsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('file_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('ext', models.CharField(blank=True, editable=False, max_length=100, verbose_name='file extension')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('name', models.CharField(choices=[('DESCRIPTION', 'Описание'), ('PRESENTATION', 'Презентация'), ('METHOD', 'Способ применения')], max_length=100, verbose_name='Тип документа')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='catalogue.ProductDocuments')),
            ],
            options={
                'verbose_name': 'Документ (перевод)',
                'verbose_name_plural': 'Документы (перевод)',
            },
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('file', models.FileField(null=True, upload_to='temp')),
                ('file_url', models.CharField(blank=True, editable=False, max_length=1000)),
                ('ext', models.CharField(blank=True, editable=False, max_length=100, verbose_name='file extension')),
                ('name', models.CharField(choices=[('FDA', 'FDA'), ('CE', 'CE'), ('CHI', 'CHI')], max_length=100, verbose_name='Тип сертфиката')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-num'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.ProductType', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='catalogue.Category')),
            ],
            options={
                'verbose_name': 'Категория (перевод)',
                'verbose_name_plural': 'Категории (перевод)',
            },
        ),
    ]
