# Generated by Django 2.2.10 on 2020-05-16 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
