# Generated by Django 2.2.10 on 2020-12-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Входная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Розничная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Старая розничная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_old_ua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Старая розничная цена UA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Розничная цена UA'),
        ),
    ]
