# Generated by Django 2.2.10 on 2020-05-16 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20200516_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_start',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало большого опта'),
        ),
        migrations.AddField(
            model_name='category',
            name='md_start',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало среднгего опта'),
        ),
        migrations.AddField(
            model_name='category',
            name='sm_start',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало малого опта'),
        ),
        migrations.AddField(
            model_name='product',
            name='bg_start',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало большого опта'),
        ),
        migrations.AddField(
            model_name='product',
            name='md_start',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало среднгего опта'),
        ),
        migrations.AddField(
            model_name='product',
            name='sm_start',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Начало малого опта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Цена')),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'История цен',
                'verbose_name_plural': 'История цен',
                'ordering': ['-update'],
            },
        ),
    ]
